name 'jenkins_server'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures jenkins_server'
long_description 'Installs/Configures jenkins_server'
version '0.1.6'
depends 'jenkins-server'
