name 'do_tut2'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures do_tut2'
long_description 'Installs/Configures do_tut2'
version '0.1.0'
